# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 16 Pro Max"
])

workspace("Divido.xcworkspace")

ios_version("26.5")

languages([
  "en-US",
  "de-DE",
  "fr-FR",
  "es-ES"
])

# The name of the scheme which contains the UI Tests
scheme("DividoUITests")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Override the status bar to Apple's marketing defaults (9:41, full battery/wifi/signal)
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
